Try to fix windows checkout

diff --git a/.azure-pipelines/steps/clone-repo.yml b/.azure-pipelines/steps/clone-repo.yml
--- a/.azure-pipelines/steps/clone-repo.yml
+++ b/.azure-pipelines/steps/clone-repo.yml
@@ -12,8 +12,6 @@ steps:
       echo "Checking out merge commit for ${{ parameters.masterCommitId }} and $prBranch"
       git version
       git lfs version
-      echo "Updating git config ..."
-      git config init.defaultBranch master
       echo "Initializing repository at $BUILD_REPOSITORY_LOCALPATH ..."
       git init "$BUILD_REPOSITORY_LOCALPATH"
       echo "Adding remote $BUILD_REPOSITORY_URI ..."
@@ -33,11 +31,14 @@ steps:
       echo "Running git clean -ffdx ..."
       git clean -ffdx
     displayName: checkout
+    condition: and(succeeded(), not(eq(variables['Agent.OS'], 'Windows_NT')))
+
   - bash: |
       echo "Updating credentials ..."
       git config user.email "gitfun@example.com"
       git config user.name "Automatic Merge"
 
+      prBranch=$SYSTEM_PULLREQUEST_SOURCEBRANCH
       echo "Merging $prBranch with ${{ parameters.masterCommitId }} ..."
       git merge ${{ parameters.masterCommitId }}
       
@@ -52,6 +53,70 @@ steps:
       echo "Merge successful"
       git status
     displayName: merge
+    condition: and(succeeded(), not(eq(variables['Agent.OS'], 'Windows_NT')))
+
+  - powershell: |
+      # As this is a pull request, we need to do a fake merge
+      # uses similar process to existing checkout task
+      $prBranch=$env:SYSTEM_PULLREQUEST_SOURCEBRANCH
+      echo "Checking out merge commit for ${{ parameters.masterCommitId }} and $prBranch"
+      echo "Checking out merge commit for ${{ parameters.masterCommitId }} and $prBranch"
+      git version
+      # Disabled in the windows version
+      # git lfs version 
+
+      $localPath=$env:BUILD_REPOSITORY_LOCALPATH
+      echo "Initializing repository at $localPath ..."
+      git init --initial-branch=master "$localPath"
+
+      cd $localPath
+
+      $repoUri=$env:BUILD_REPOSITORY_URI
+      echo "Adding remote $repoUri ..."
+      git remote add origin "$repoUri"
+
+      git config gc.auto 0
+      git config --get-all http.$repoUri.extraheader
+      git config --get-all http.extraheader
+      git config --get-regexp .*extraheader
+      git config --get-all http.proxy
+      git config http.version HTTP/1.1
+
+      echo "Force fetching master and $prBranch ..."
+      echo "git fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin +refs/heads/master:refs/remotes/origin/master +refs/heads/${prBranch}:refs/remotes/origin/${prBranch}"
+      git fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin +refs/heads/master:refs/remotes/origin/master +refs/heads/${prBranch}:refs/remotes/origin/${prBranch}
+
+      echo "Checking out $prBranch..."
+      git checkout --force $prBranch
+
+      echo "Resetting $prBranch to origin/$prBranch ..."
+      git reset origin/$prBranch --hard
+      echo "Running git clean -ffdx ..."
+      git clean -ffdx
+    displayName: checkout
+    condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
+
+  - powershell: |
+      echo "Updating credentials ..."
+      git config user.email "gitfun@example.com"
+      git config user.name "Automatic Merge"
+      $prBranch=$env:SYSTEM_PULLREQUEST_SOURCEBRANCH
+
+      echo "Merging $prBranch with ${{ parameters.masterCommitId }} ..."
+      git merge ${{ parameters.masterCommitId }}
+
+      $mergeInProgress=$LASTEXITCODE
+      if("$mergeInProgress" -ne "0") {
+        echo "Merge failed, rolling back ..."
+        git merge --abort
+        exit 1;
+      }
+
+      echo "Merge successful"
+      git status
+    displayName: merge
+    condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
+
 - ${{ else }}:
   - checkout: self
     clean: true
