test

diff --git a/.gitlab/benchmarks/microbenchmarks.yml b/.gitlab/benchmarks/microbenchmarks.yml
--- a/.gitlab/benchmarks/microbenchmarks.yml
+++ b/.gitlab/benchmarks/microbenchmarks.yml
@@ -1,3 +1,16 @@
+dd-octo-sts-setup:
+  before_script:
+    - |
+      set +e
+      error_output=$({ dd-octo-sts token --scope DataDog/dd-trace-dotnet --policy gitlab.github-access.read-contents > "/tmp/github-token"; } 2>&1)
+      exit_code=$?
+      if [ $exit_code -ne 0 ]; then
+        echo "ERROR: Failed to retrieve a GitHub token with dd-octo-sts gitlab.github-access.read-contents policy."
+        echo "Original error: $error_output"
+        echo "Continuing execution anyway..."
+      fi
+      set -e
+
 stages:
   - build
   - benchmarks
@@ -28,16 +41,7 @@ build-dd-trace-dotnet-microbenchmarks-ami:
     # based on an instance that is created in this job
     CLEANUP: "true"
   before_script:
-    - |
-      set +e
-      error_output=$({ dd-octo-sts token --scope DataDog/dd-trace-dotnet --policy gitlab.github-access.read-contents > "/tmp/github-token"; } 2>&1)
-      exit_code=$?
-      if [ $exit_code -ne 0 ]; then
-        echo "ERROR: Failed to retrieve a GitHub token with dd-octo-sts gitlab.github-access.read-contents policy."
-        echo "Original error: $error_output"
-        echo "Continuing execution anyway..."
-      fi
-      set -e
+    - !reference [dd-octo-sts-setup, before_script]
   script:
     - git clone --branch $BP_INFRA_BENCHMARKING_PLATFORM_BRANCH https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ddbuild.io/DataDog/benchmarking-platform platform
     # TODO: Uncomment the second line, remove the first one
@@ -98,6 +102,8 @@ run-benchmarks:
     paths:
       - platform/artifacts/
     expire_in: 1 day
+  before_script:
+    - !reference [dd-octo-sts-setup, before_script]
   script:
     - git clone --branch $BP_INFRA_BENCHMARKING_PLATFORM_BRANCH https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ddbuild.io/DataDog/benchmarking-platform platform
     - ./platform/steps/run-windows-benchmarks.sh
